Tokyo_level = [
    '                                ',
    '                                ',
    '                        H       ',
    '                      XXXXXX    ',
    '                                ',
    '             X                  ',
    '  H                             ',
    '  X                             ',
    '                                ',
    '         X                      ',
    '                                ',
    '                             2  ',
    '   X               X            ',
    '                                ',
    '                          XXXXXX',
    '            X                   ',
    '      1X    XT        X     H H ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', ]

Forest_level = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '               XX               ',
    '               XX               ',
    '               XX               ',
    'H    1X_ _ _ _ XX_ _ _ _ X2    H',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', ]

Industrial_level = [
    '                                ',
    '                                ',
    '               H                ',
    '           XXXXXXXXXX           ',
    '                                ',
    '                                ',
    '                                ',
    '  H                             ',
    '  XXX                        H  ',
    '                           XXX  ',
    '             _ _ _              ',
    '                                ',
    '    XXX                   XXX   ',
    '                                ',
    '                                ',
    '      XXS S S S S S S S XX      ',
    '1     XX                XX    2 ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', ]

Apocalypsis = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    'H                              H',
    'XXX_                       _ XXX',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '       X                X       ',
    '  1    XX  H   H    H  XX    2  ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', ]

Plain = [
    '                                ',
    '                                ',
    '             X    X              ',
    '  H         HX    XH        H    ',
    'XXXXXXXXXXXXXX    XXXXXXXXXXXXXXX',
    '                                ',
    '                                ',
    '             X    X              ',
    'XXXXXX   XXXXX    XXXXX    XXXXXX',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '      XXXX            XXXX       ',
    '                                ',
    '                                ',
    '  1       H   T         H    2  ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', ]

tile_size = 40
screen_width = 1280
screen_height = 720
