Tokyo_level = [
    '                                ',
    '                                ',
    '                                ',
    '                      XXXXXX    ',
    '                                ',
    '             X                  ',
    '                                ',
    '  X                             ',
    '                    X           ',
    '                                ',
    '         X                      ',
    '                             2  ',
    '   X               X       XXX  ',
    '                                ',
    '                                ',
    '            X  __            XXXX ',
    '      1     X                   ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Forest_level = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                __                ',
    '               XX               ',
    '               XX               ',
    '               XX               ',
    '     1X        XX        X2     ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Industrial_level = [
    '                                ',
    '                                ',
    '                                ',
    '          XXXXXXXXXX            ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '  XXX                           ',
    '                           XXX  ',
    '             _ _ _              ',
    '                                ',
    '    XXX                   XXX   ',
    '                                ',
    '                                ',
    '      XXS S S S S S S S XX      ',
    '1     XX                XX    2 ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Apocalypsis = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    'XXXXX                      XXXXX',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '      X        __         X       ',
    '1     XX      XXX      XX    2 ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Plain = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '               __                 ',
    ' 1           XXXX           2   ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

tile_size = 40
screen_width = 1280
screen_height = 720
