Tokyo_level = [
    '                                ',
    '                                ',
    '                                ',
    '                      XXXXXX    ',
    '                                ',
    '             X                  ',
    '                                ',
    '  X                             ',
    '                    X           ',
    '                                ',
    '         X                      ',
    '                             2  ',
    '   X               X       XXX  ',
    '                                ',
    '                                ',
    '            X              XXXX ',
    '      1     X        H          ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Forest_level = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                H               ',
    '               XX               ',
    '               XX               ',
    '               XX               ',
    '     1X_ _ _ _ XX_ _ _ _ X2     ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Industrial_level = [
    '                                ',
    '                                ',
    '                                ',
    '           XXXXXXXXXX           ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '  XXX                       H   ',
    '                           XXX  ',
    '             _ _ _              ',
    '                                ',
    '    XXX                   XXX   ',
    '                                ',
    '                                ',
    '      XXS S S S S S S S XX      ',
    '1     XX                XX    2 ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Apocalypsis = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    'XXXXX                      XXXXX',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '      X                 X       ',
    '  1   XX       H        XX   2  ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

Plain = [
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    '                                ',
    ' 1           XXXX  H        2   ',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',]

tile_size = 40
screen_width = 1280
screen_height = 720
